mode: chatops
silent: true
branchName: '${issue.number}-${issue.title,}'
gitSafeReplacementChar: '-'
branches:
  - label:
      - bug🐞
    prefix: bug/
  - label:
      - feature-request👓
    prefix: feature/
  - label:
      - documentation📄
    prefix: documentation/
experimental:
  branchNameArgument: true
