name: Docker Hub Push

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      IMAGE_TAG:
        required: false
        default: ${{ github.repository }}:latest
        type: string
      PLATFORMS:
        required: false
        default: linux/amd64,linux/arm64,linux/arm64/v8
        type: string
      FILE:
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          platforms: ${{ inputs.PLATFORMS }}
          tags: ${{ inputs.IMAGE_TAG }}
          file: ${{ inputs.FILE }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
