name: GitHub Release & Tag Cleaner

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      RELEASE_CLEANUP_PATTERN:
        required: false
        default: '[\s\S]*'
        type: string
jobs:
  release-cleanup:
    name: GitHub Cleanup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: nikhilbadyal/ghaction-rm-releases@dd944d88262e0ca5e68c8fed16e2d581103ef6d6 # v0.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RELEASE_PATTERN: ${{ inputs.RELEASE_CLEANUP_PATTERN }}
