name: GitHub Cleaner

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      GITHUB_REPOSITORY:
        required: false
        default: ${{ github.repository }}
        type: string
      RELEASE_CLEANUP_PATTERN:
        required: false
        default: '[\s\S]*'
        type: string
jobs:
  release-cleanup:
    name: GitHub Cleanup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: nikhilbadyal/ghaction-rm-releases@v0.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RELEASE_PATTERN: ${{ inputs.RELEASE_CLEANUP_PATTERN }}
  #https://github.com/orgs/community/discussions/8488
  workflow-cleanup:
    name: RM Workflows
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          workflow_ids=($(gh api repos/"$GITHUB_REPOSITORY"/actions/workflows | jq '.workflows[] | .id'))
          for workflow_id in "${workflow_ids[@]}"
          do
            echo "Listing runs for the workflow ID $workflow_id"
            run_ids=($(gh api repos/"$GITHUB_REPOSITORY"/actions/workflows/"$workflow_id"/runs?status=completed --paginate | jq '.workflow_runs[].id'))
            for run_id in "${run_ids[@]}"
            do
              echo "Deleting Run ID $run_id"
              gh api repos/"$GITHUB_REPOSITORY"/actions/runs/"$run_id" -X DELETE >/dev/null
            done
          done
          echo "Deleting orphan workflows"
          run_ids=($(gh api repos/"$GITHUB_REPOSITORY"/actions/runs?status=completed --paginate | jq '.workflow_runs[].id'))
          for run_id in "${run_ids[@]}"
          do
            echo "Deleting Run ID $run_id"
            gh api repos/"$GITHUB_REPOSITORY"/actions/runs/"$run_id" -X DELETE >/dev/null
          done
  
