name: Org-wide pre-commit updater (via GitHub App)


on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 'latest'

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install pre-commit
          npm install

      - name: Run pre-commit updater
        env:
          PRE_COMMIT_UPDATER_APP_ID: ${{ secrets.PRE_COMMIT_UPDATER_APP_ID }}
          PRE_COMMIT_UPDATER_APP_UID: ${{ secrets.PRE_COMMIT_UPDATER_APP_UID }}
          PRE_COMMIT_UPDATER_OWNER: ${{ secrets.PRE_COMMIT_UPDATER_OWNER }}
          PRE_COMMIT_UPDATER_PRIVATE_KEY_BASE64: ${{ secrets.PRE_COMMIT_UPDATER_PRIVATE_KEY_BASE64 }}
        run: node precommit-updater.mjs
