name: Python Linter

on:
  workflow_call:
    inputs:
      CACHE_DEPENDENCY_PATH:
        required: false
        default: requirements.txt
        type: string
      PYTHON_VERSION:
        required: false
        default: '3.x'
        type: string

jobs:
  linter:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: ${{ inputs.CACHE_DEPENDENCY_PATH }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
