name: Python Pre-commit updater

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      CACHE_DEPENDENCY_PATH:
        required: false
        default: requirements.txt
        type: string
      PYTHON_VERSION:
        required: false
        default: '3.x'
        type: string

permissions:
  contents: read

jobs:
  auto-update:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: ${{ inputs.CACHE_DEPENDENCY_PATH }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Updated Hooks
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: ⬆️Update pre-commit hooks
          commit-message: ⬆️updated pre-commit hooks
          body: ✨Update versions of tools in pre-commit configs to latest version
          labels: pre-commit✨
