name: Python Linter

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_call:
    inputs:
      CACHE_DEPENDENCY_PATH:
        required: false
        default: requirements.txt
        type: string
      PYTHON_VERSION:
        required: false
        default: '3.x'
        type: string

  workflow_dispatch:


jobs:
  linter:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: ${{ inputs.CACHE_DEPENDENCY_PATH }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
