name: Telegram Uploader (GitHub releases)

on:
  workflow_call:
    secrets:
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      STICKER_ID:
        required: true
      CHANGELOG_GITHUB_REPOSITORY:
        required: false
      DOWNLOAD_GITHUB_REPOSITORY:
        required: false
      ASSETS_PATTERN:
        required: false
      SEND_MESSAGE:
        required: false
      SEND_STICKER:
        required: false
      MESSAGE:
        required: false

jobs:
  tg-upload:
    name: Telegram Upload
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Telegram
        uses: nikhilbadyal/ghaction-telegram-uploader@main
        with:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STICKER_ID: ${{ secrets.STICKER_ID }}
          CHANGELOG_GITHUB_REPOSITORY: ${{ secrets.CHANGELOG_GITHUB_REPOSITORY }}
          DOWNLOAD_GITHUB_REPOSITORY: ${{ secrets.DOWNLOAD_GITHUB_REPOSITORY }}
          ASSETS_PATTERN: ${{ secrets.ASSETS_PATTERN }}
          SEND_MESSAGE: ${{ secrets.SEND_MESSAGE }}
          SEND_STICKER: ${{ secrets.SEND_STICKER }}
          MESSAGE: ${{ secrets.MESSAGE }}
