name: Telegram GitHub Upload

on:
  workflow_call:
    secrets:
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
    inputs:
      STICKER_ID:
        required: true
      CHANGELOG_GITHUB_REPOSITORY:
        required: false

jobs:
  tg-upload:
    name: Telegram Upload
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Telegram
        uses: nikhilbadyal/ghaction-telegram-uploader@main
        with:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STICKER_ID: ${{ inputs.STICKER_ID }}
          CHANGELOG_GITHUB_REPOSITORY: ${{ inputs.CHANGELOG_GITHUB_REPOSITORY }}
