name: VirusTotal GitHub Scan

on:
  workflow_call:
    secrets:
      VT_API_KEY:
        required: true
      GH_TOKEN:
        required: true
    inputs:
      FILES:
        required: true
      REQUEST_RATE:
        required: false
        default: 4

jobs:
  virustotal:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: nikhilbadyal/ghaction-virustotal@master
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GH_TOKEN }}
          request_rate: ${{ inputs.REQUEST_RATE }}
          files: ${{ inputs.FILES }}
